# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2022-07-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0008_auto_20220210_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingad',
            name='youtube_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoad',
            name='youtube_kids',
            field=models.BooleanField(default=False),
        ),
    ]
