# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2023-01-03 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreToDB', '0010_auto_20220705_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
